// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv9oO6vLZHPI8GM--_oRBPp0qvI0dZmtc',
    appId: '1:696399938110:web:b0857c6f2e61d4043f476f',
    messagingSenderId: '696399938110',
    projectId: 'reddit-clone-403b5',
    authDomain: 'reddit-clone-403b5.firebaseapp.com',
    storageBucket: 'reddit-clone-403b5.appspot.com',
    measurementId: 'G-PZ1V3H4S92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSWw5Ak0bri35Bk7mcbaks8vTr7T-iiBY',
    appId: '1:696399938110:android:418ce189d6b3ace73f476f',
    messagingSenderId: '696399938110',
    projectId: 'reddit-clone-403b5',
    storageBucket: 'reddit-clone-403b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyDTmtLbVeLRX6h11dAArrjfiEU4yC1P8',
    appId: '1:696399938110:ios:f5ab3fba79523b523f476f',
    messagingSenderId: '696399938110',
    projectId: 'reddit-clone-403b5',
    storageBucket: 'reddit-clone-403b5.appspot.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyDTmtLbVeLRX6h11dAArrjfiEU4yC1P8',
    appId: '1:696399938110:ios:ea4667a34bdcaed83f476f',
    messagingSenderId: '696399938110',
    projectId: 'reddit-clone-403b5',
    storageBucket: 'reddit-clone-403b5.appspot.com',
    iosBundleId: 'com.example.reddit.RunnerTests',
  );
}
